# Generated by Django 5.1.7 on 2025-05-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_corner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
