# Generated by Django 5.1.7 on 2025-05-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_corner', '0002_alter_description_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='frontImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
