# Generated by Django 5.1.7 on 2025-05-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_corner', '0004_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline_Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.TextField()),
                ('subject', models.TextField()),
                ('timeline', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
