# Generated by Django 5.1.7 on 2025-05-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_corner', '0005_timeline_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('link', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('video', models.FileField(blank=True, null=True, upload_to='projects/')),
            ],
        ),
    ]
