# Generated by Django 5.1.7 on 2025-05-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_corner', '0006_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('headline', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
    ]
